namespace RGO.Models
{
    public enum CommodityType
    {
        AlienFossils = 0,
        Anomalies = 1,
        AntimatterSpeck = 2,
        BaryonicCatalyst = 3,
        Bioweapons = 4,
        Ceramics = 5,
        Components = 6,
        CounterfeitGoods = 7,
        DataCubes = 8,
        DesignerClothes = 9,
        DevotionalArt = 10,
        Diamonds = 11,
        DryAgedYikyak = 12,
        Explosives = 13,
        FineArt = 14,
        GoldOre = 15,
        GreelWhiskey = 16,
        GreenBlueLabel = 17,
        HijackedValuables = 18,
        HitchcockCoronas = 19,
        HolovangelismVids = 20,
        Holovids = 21,
        HumanOrgans = 22,
        HumanTransplants = 23,
        IronOre = 24,
        MultiPlayerGames = 24,
        NanoFibers = 25,
        NarcoCola = 26,
        ObtaniumOre = 27,
        ProgenitorShard = 28,
        PulpNovels = 29,
        PureWater = 30,
        RedStarBeer = 31,
        ReligiousTracts = 32,
        RobotModules =33,
        RobotWarriors =34,
        RobotWorkers =35,
        Scag = 36,
        SoyPaste = 37,
        Steel = 38,
        StolenFreight = 39,
        SusiGradeStarfish = 40,
        Thralls = 41,
        VatGrownTissue = 42,
        Void = 43,
        Processors = 44,
        AlienSpecimens = 45,
        AlienArtifacts = 46,
        BlackMarketWeapons = 47        
    }
}